import Head from 'next/head';
import '../styles/globals.css';``
import './tw.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat"
          rel="stylesheet"
        />
        <title>Nick White</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/volcano_mountain_icon_187744.ico" style={{color: "white"}}/>
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;