import Head from 'next/head';
import '../styles/globals.css'; ``
import './tw.css';
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { CacheProvider } from '@chakra-ui/next-js';
import { Rubik } from 'next/font/google';

// Set theme for Chakra UI
const colors = {
  brand: {
    900: '#1a365d',
    800: '#153e75',
    700: '#2a69ac',
  },
}

export const theme = extendTheme({
  colors,
  fonts: {
    heading: 'var(--font-rubik)',
    body: 'var(--font-rubik)',
  },
  styles: {
    global: {
      body: {
        bg: "Snow"
      }
    }
  }
  
});

// Set font for Rubik
const rubik = Rubik({ subsets: ['latin'] });

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat"
          rel="stylesheet"
        />
        <title>Serapio Labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/volcano_mountain_icon_187744.ico" style={{ color: "white" }} />

        <script src='https://jeromeetienne.github.io/threex.terrain/examples/vendor/three.js/build/three-min.js'></script>
        <script src='https://jeromeetienne.github.io/threex.terrain/examples/vendor/three.js/examples/js/SimplexNoise.js'></script>
        <script src='https://jeromeetienne.github.io/threex.terrain/threex.terrain.js'></script>
      </Head>
      <style jsx global>
        {`
        :root {
          --font-rubik: ${rubik.style.fontFamily};
        }
      `}
      </style>
      <CacheProvider>
        <ChakraProvider theme={theme}>
          <Component {...pageProps} />
        </ChakraProvider>
      </CacheProvider>
    </>
  );
}

export default MyApp;